# Generated by Django 3.2.3 on 2022-07-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peernadaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='keyword1',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='keyword2',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='keyword3',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='main_act',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mbti',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
